Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -6,20 +6,20 @@ on:
   pull_request:
     branches: [ "main" ]
   schedule:
-    - cron: '30 1 * * *'
+    - cron: '0 15 * * *'  # 한국 시간 기준 00시 실행
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
     - uses: actions/checkout@v4
-    - name: Set up Python ${{ matrix.python-version }}
+
+    - name: Set up Python
       uses: actions/setup-python@v3
       with:
-        python-version: ${{ matrix.python-version }}
-        
+        python-version: '3.10'
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
@@ -32,10 +32,13 @@ jobs:
         pip install lxml
         pip install selenium
         pip install webdriver_manager
-       
-    - name: Run Python script
+
+    - name: Run Python script with retry
       run: |
-        python3 travelrank.py
+        RETRIES=3
+        for i in $(seq 1 $RETRIES); do
+          python3 travelrank.py && break || echo "Attempt $i failed. Retrying in 10 seconds..." && sleep 10
+        done
 
     - name: Find generated folders
       id: find_folders
@@ -52,7 +55,7 @@ jobs:
 
     - name: Configure Git
       run: |
-        git config --global user.email "rhthrck12@gmail.com"
+        git config --global user.email "rhthrck12@gmail.com"
         git config --global user.name "123dd654"
 
     - name: Commit changes
